// _tmp_pipeline/compounds.mjs
// Greedy-first atom dictionary.
// These multi-char strings MUST be matched as single units BEFORE any
// per-character operator matcher runs, otherwise their parts will fire
// the wrong operators (e.g. というか would fire QUOTATIVE + か = wrong).
//
// Ordered by length (longest first) at export time so a left-to-right
// longest-match tokenizer can consume them safely.

/** @type {{surface:string, kind:string, note?:string}[]} */
const RAW_COMPOUNDS = [
  // ===== nominalizer + copula clusters =====
  { surface: 'ということなんですけれども', kind: 'meta-frame-hedge' },
  { surface: 'というふうに思います',     kind: 'meta-think' },
  { surface: 'ということになります',     kind: 'meta-result' },
  { surface: 'ということになる',         kind: 'meta-result' },
  { surface: 'ということなんです',       kind: 'meta-explanation' },
  { surface: 'ということなんだ',         kind: 'meta-explanation' },
  { surface: 'ということだ',             kind: 'meta-conclude' },
  { surface: 'ということです',           kind: 'meta-conclude' },
  { surface: 'ということで',             kind: 'meta-segue' },
  { surface: 'ということは',             kind: 'meta-inference' },
  { surface: 'ということを',             kind: 'meta-object' },
  { surface: 'ということが',             kind: 'meta-subject' },
  { surface: 'ということ',               kind: 'meta-noun' },
  { surface: 'というよりも',             kind: 'reformulate-stronger' },
  { surface: 'というより',               kind: 'reformulate-stronger' },
  { surface: 'というか',                 kind: 'reformulate-repair' },
  { surface: 'というのは',               kind: 'perspective-stage-open' },
  { surface: 'というのが',               kind: 'definition-subject' },
  { surface: 'というのを',               kind: 'definition-object' },
  { surface: 'というのも',               kind: 'definition-also' },
  { surface: 'というふうな',             kind: 'meta-like' },
  { surface: 'というふうに',             kind: 'meta-manner' },
  { surface: 'というわけです',           kind: 'meta-conclude-soft' },
  { surface: 'というわけで',             kind: 'meta-segue' },
  { surface: 'というわけ',               kind: 'meta-noun' },
  { surface: 'という感じ',               kind: 'approximative' },
  { surface: 'という意味で',             kind: 'reframe' },
  { surface: 'という意味',               kind: 'reframe-noun' },
  { surface: 'というもの',               kind: 'meta-thing' },
  { surface: 'というところ',             kind: 'meta-place' },
  { surface: 'というところで',           kind: 'meta-place-loc' },
  { surface: 'というところの',           kind: 'meta-place-mod' },
  { surface: 'と言っても',               kind: 'concede-quote' },
  { surface: 'と言いますか',             kind: 'reformulate-polite' },
  { surface: 'と言うか',                 kind: 'reformulate-repair' },
  { surface: 'と思います',               kind: 'epistemic-think-pol' },
  { surface: 'と思う',                   kind: 'epistemic-think' },
  { surface: 'と思って',                 kind: 'motive-intent' },
  { surface: 'と思ってる',               kind: 'motive-intent-cont' },
  { surface: 'と思っていた',             kind: 'motive-intent-past' },
  { surface: 'と感じます',               kind: 'epistemic-feel-pol' },
  { surface: 'と感じる',                 kind: 'epistemic-feel' },
  { surface: 'と考えます',               kind: 'epistemic-consider-pol' },
  { surface: 'と考える',                 kind: 'epistemic-consider' },
  { surface: 'という',                   kind: 'quotative-attrib' },

  // ===== って-cluster (colloquial quotative) =====
  { surface: 'ってことなんです',         kind: 'meta-explanation-c' },
  { surface: 'ってことなんだ',           kind: 'meta-explanation-c' },
  { surface: 'ってことになる',           kind: 'meta-result-c' },
  { surface: 'ってことだよね',           kind: 'meta-confirm-c' },
  { surface: 'ってことですよね',         kind: 'meta-confirm-c-pol' },
  { surface: 'ってことになります',       kind: 'meta-result-c-pol' },
  { surface: 'ってことか',               kind: 'meta-infer-c' },
  { surface: 'ってこと',                 kind: 'meta-noun-c' },
  { surface: 'っていうのは',             kind: 'perspective-stage-open-c' },
  { surface: 'っていうのが',             kind: 'definition-subject-c' },
  { surface: 'っていうのも',             kind: 'definition-also-c' },
  { surface: 'っていうわけ',             kind: 'meta-conclude-c' },
  { surface: 'っていうか',               kind: 'reformulate-repair-c' },
  { surface: 'っていうふうに',           kind: 'meta-manner-c' },
  { surface: 'っていう感じ',             kind: 'approximative-c' },
  { surface: 'っていう',                 kind: 'quotative-attrib-c' },
  { surface: 'って言ってた',             kind: 'quote-past' },
  { surface: 'って言われ',               kind: 'quote-passive' },
  { surface: 'って思って',               kind: 'motive-intent-c' },
  { surface: 'って感じ',                 kind: 'approximative-c2' },

  // ===== confirmation / ground-claim cluster =====
  { surface: 'じゃないですかね',         kind: 'ground-claim-hedged-pol' },
  { surface: 'じゃないですか',           kind: 'ground-claim-pol' },
  { surface: 'じゃないかな',             kind: 'epistemic-soften' },
  { surface: 'じゃないか',               kind: 'ground-claim' },
  { surface: 'じゃない',                 kind: 'negation-or-confirm' },
  { surface: 'んじゃないですかね',       kind: 'ground-claim-hedged-pol2' },
  { surface: 'んじゃないですか',         kind: 'ground-claim-explain-pol' },
  { surface: 'んじゃないかな',           kind: 'epistemic-soften2' },
  { surface: 'んじゃない',               kind: 'ground-claim-explain' },
  { surface: 'ですよね',                 kind: 'confirm-pol' },
  { surface: 'ですね',                   kind: 'agree-pol' },
  { surface: 'ですよ',                   kind: 'assert-pol' },
  { surface: 'ですか',                   kind: 'question-pol' },
  { surface: 'でしょうね',               kind: 'conjecture-align' },
  { surface: 'でしょうか',               kind: 'conjecture-probe' },
  { surface: 'でしょう',                 kind: 'conjecture-state' },
  { surface: 'だろうね',                 kind: 'conjecture-align' },
  { surface: 'だろうか',                 kind: 'conjecture-probe' },
  { surface: 'だろう',                   kind: 'conjecture-state' },
  { surface: 'でしょ',                   kind: 'conjecture-appeal' },
  { surface: 'だろ',                     kind: 'conjecture-appeal' },
  { surface: 'だよね',                   kind: 'confirm-c2' },
  { surface: 'だよな',                   kind: 'confirm-c3' },
  { surface: 'だね',                     kind: 'agree-c' },
  { surface: 'だな',                     kind: 'agree-c-self' },
  { surface: 'よね',                     kind: 'confirm-soft' },
  { surface: 'もんね',                   kind: 'reason-shared' },
  { surface: 'もんな',                   kind: 'reason-shared-self' },
  { surface: 'もん',                     kind: 'reason-noun-c' },

  // ===== explanation / nominalized assertion (explain-frame) =====
  { surface: 'んですけれども',           kind: 'explain-hedge' },
  { surface: 'んですけれど',             kind: 'explain-hedge' },
  { surface: 'んですけど',               kind: 'explain-hedge' },
  { surface: 'んですよね',               kind: 'explain-confirm' },
  { surface: 'んですから',               kind: 'explain-cause' },
  { surface: 'んですよ',                 kind: 'explain-reveal' },
  { surface: 'んですね',                 kind: 'explain-align' },
  { surface: 'んですか',                 kind: 'explain-q' },
  { surface: 'んです',                   kind: 'explain-state' },
  { surface: 'のですが',                 kind: 'explain-hedge' },
  { surface: 'のですけれども',           kind: 'explain-hedge' },
  { surface: 'のです',                   kind: 'explain-state' },
  { surface: 'のだ',                     kind: 'explain-state' },
  { surface: 'んだよね',                 kind: 'explain-confirm' },
  { surface: 'んだから',                 kind: 'explain-cause' },
  { surface: 'んだよ',                   kind: 'explain-reveal' },
  { surface: 'んだね',                   kind: 'explain-align' },
  { surface: 'んだ',                     kind: 'explain-state' },
  { surface: 'んだけれども',             kind: 'explain-hedge' },
  { surface: 'んだけれど',               kind: 'explain-hedge' },
  { surface: 'んだけど',                 kind: 'explain-hedge' },
  { surface: 'わけですけれども',         kind: 'reason-concede' },
  { surface: 'わけですけども',           kind: 'reason-concede' },
  { surface: 'わけですけれど',           kind: 'reason-concede' },
  { surface: 'わけですけど',             kind: 'reason-concede' },
  { surface: 'わけだけれども',           kind: 'reason-concede' },
  { surface: 'わけだけども',             kind: 'reason-concede' },
  { surface: 'わけだけれど',             kind: 'reason-concede' },
  { surface: 'わけだけど',               kind: 'reason-concede' },
  { surface: 'わけですから',             kind: 'reason-cause' },
  { surface: 'わけだから',               kind: 'reason-cause' },
  { surface: 'わけでありまして',         kind: 'reason-ground' },
  { surface: 'わけでして',               kind: 'reason-ground' },
  { surface: 'わけですよね',             kind: 'reason-align' },
  { surface: 'わけだよね',               kind: 'reason-align' },
  { surface: 'わけですよ',               kind: 'reason-reveal' },
  { surface: 'わけだよ',                 kind: 'reason-reveal' },
  { surface: 'わけですね',               kind: 'reason-align' },
  { surface: 'わけだね',                 kind: 'reason-align' },
  { surface: 'わけです',                 kind: 'reason-state' },
  { surface: 'わけで',                   kind: 'reason-ground' },
  { surface: 'わけだ',                   kind: 'reason-state' },
  { surface: 'わけがない',               kind: 'rule-out' },
  { surface: 'わけにはいかない',         kind: 'modal-impermissible' },
  { surface: 'わけ',                     kind: 'reason-noun' },

  // ===== epistemic / evidential =====
  { surface: 'かもしれません',           kind: 'epistemic-may-pol' },
  { surface: 'かもしれない',             kind: 'epistemic-may' },
  { surface: 'かもしれん',               kind: 'epistemic-may-c' },
  { surface: 'かもね',                   kind: 'epistemic-may-soft' },
  { surface: 'かも',                     kind: 'epistemic-may-min' },
  { surface: 'はずです',                 kind: 'epistemic-expect-pol' },
  { surface: 'はずだ',                   kind: 'epistemic-expect' },
  { surface: 'はずがない',               kind: 'epistemic-rule-out' },
  { surface: 'はず',                     kind: 'epistemic-expect-n' },
  { surface: 'みたいです',               kind: 'evidential-seem-pol' },
  { surface: 'みたいな',                 kind: 'approximative-attr' },
  { surface: 'みたいに',                 kind: 'approximative-adv' },
  { surface: 'みたい',                   kind: 'evidential-seem' },
  { surface: 'らしいです',               kind: 'hearsay-pol' },
  { surface: 'らしい',                   kind: 'hearsay-or-typical' },
  { surface: 'ようです',                 kind: 'evidential-appear-pol' },
  { surface: 'ようだ',                   kind: 'evidential-appear' },
  { surface: 'そうです',                 kind: 'hearsay-or-appear-pol' },
  { surface: 'そうだ',                   kind: 'hearsay-or-appear' },
  { surface: 'っぽい',                   kind: 'approximative-typical' },

  // ===== conditional / consequence =====
  { surface: 'のだとしたら',             kind: 'cond-explain' },
  { surface: 'のだとすると',             kind: 'cond-explain2' },
  { surface: 'だとしたら',               kind: 'cond-hypothetical' },
  { surface: 'だとすると',               kind: 'cond-derive' },
  { surface: 'だとしても',               kind: 'cond-concede' },
  { surface: 'としたら',                 kind: 'cond-supposing' },
  { surface: 'とすると',                 kind: 'cond-derive2' },
  { surface: 'としても',                 kind: 'cond-concede2' },
  { surface: 'にしても',                 kind: 'cond-concede3' },
  { surface: 'にしては',                 kind: 'cond-given-that' },
  { surface: 'にせよ',                   kind: 'cond-concede-formal' },
  { surface: 'にしろ',                   kind: 'cond-concede-cmd' },
  { surface: 'であっても',               kind: 'cond-concede-even' },
  { surface: 'にもかかわらず',           kind: 'concessive-strong' },
  { surface: 'にも関わらず',             kind: 'concessive-strong2' },
  { surface: 'ものの',                   kind: 'concessive-formal' },
  { surface: 'けれども',                 kind: 'concessive' },
  { surface: 'けれど',                   kind: 'concessive-soft' },
  { surface: 'けども',                   kind: 'concessive-c' },
  { surface: 'けど',                     kind: 'concessive-min' },
  { surface: 'たって',                   kind: 'concessive-c2' },
  { surface: 'ても',                     kind: 'concessive-suffix' },

  // ===== causal / inferential =====
  { surface: 'からこそ',                 kind: 'causal-emphatic' },
  { surface: 'からといって',             kind: 'reject-reason' },
  { surface: 'からですね',               kind: 'reason-fronted-pol' },
  { surface: 'からですよ',               kind: 'reason-assert-pol' },
  { surface: 'からだ',                   kind: 'reason-fronted' },
  { surface: 'からね',                   kind: 'reason-shared-c' },
  { surface: 'からよ',                   kind: 'reason-assert-c' },
  { surface: 'から',                     kind: 'causal' },
  { surface: 'ためです',                 kind: 'purpose-pol' },
  { surface: 'ために',                   kind: 'purpose-adv' },
  { surface: 'ため',                     kind: 'purpose-n' },
  { surface: 'ので',                     kind: 'causal-soft' },
  { surface: 'のでね',                   kind: 'causal-soft-c' },
  { surface: 'からして',                 kind: 'from-the-fact' },
  { surface: 'したがって',               kind: 'inferential-formal' },
  { surface: 'よって',                   kind: 'inferential-formal2' },
  { surface: 'だから',                   kind: 'causal-discourse' },
  { surface: 'それで',                   kind: 'sequential-discourse' },
  { surface: 'そのため',                 kind: 'because-of-that' },
  { surface: 'そのために',               kind: 'for-that-purpose' },
  { surface: 'その結果',                 kind: 'as-a-result' },
  { surface: 'ゆえに',                   kind: 'therefore-formal' },
  { surface: '故に',                     kind: 'therefore-formal2' },

  // ===== topic-shift / reformulation discourse markers =====
  { surface: 'ところで',                 kind: 'topic-shift' },
  { surface: 'それはそうと',             kind: 'topic-shift-aside' },
  { surface: 'そういえば',               kind: 'recall-shift' },
  { surface: 'というか',                 kind: 'reformulate-repair' }, // dup safety
  { surface: 'いやいや',                 kind: 'reject-strong' },
  { surface: 'いやいやいや',             kind: 'reject-strong2' },
  { surface: 'そうじゃなくて',           kind: 'repair-correct' },
  { surface: 'じゃなくて',               kind: 'repair-not-but' },
  { surface: 'ではなくて',               kind: 'repair-not-but-pol' },
  { surface: 'ではなく',                 kind: 'repair-not-but-formal' },
  { surface: 'つまり',                   kind: 'reformulate-summarize' },
  { surface: 'すなわち',                 kind: 'reformulate-formal' },
  { surface: '要するに',                 kind: 'reformulate-essence' },
  { surface: '結局',                     kind: 'conclude-after-all' },
  { surface: 'いずれにせよ',             kind: 'conclude-anyway' },
  { surface: 'いずれにしても',           kind: 'conclude-anyway2' },
  { surface: 'とにかく',                 kind: 'set-aside-move-on' },
  { surface: 'ともかく',                 kind: 'set-aside-move-on2' },
  { surface: 'まあ、',                   kind: 'hedge-discourse' },
  { surface: 'ま、',                     kind: 'hedge-discourse-min' },

  // ===== anaphoric / categorical =====
  { surface: 'そういうことで',           kind: 'class-lift-causal' },
  { surface: 'そういうことだ',           kind: 'class-lift-conclude' },
  { surface: 'そういうわけで',           kind: 'class-lift-segue' },
  { surface: 'そういうわけだ',           kind: 'class-lift-conclude2' },
  { surface: 'そういう類',               kind: 'class-lift-type' },
  { surface: 'そういう感じ',             kind: 'class-lift-approx' },
  { surface: 'そういう意味で',           kind: 'class-lift-in-sense' },
  { surface: 'そういう意味では',         kind: 'class-lift-in-sense-top' },
  { surface: 'そういう理由で',           kind: 'class-lift-reason' },
  { surface: 'そういう理由から',         kind: 'class-lift-reason2' },
  { surface: 'そういうところで',         kind: 'class-lift-place' },
  { surface: 'そういう',                 kind: 'anaphoric-typecall' },
  { surface: 'そんな感じ',               kind: 'class-lift-approx-c' },
  { surface: 'そんな',                   kind: 'anaphoric-typecall-c' },
  { surface: 'そうなった時',             kind: 'world-recall-when' },
  { surface: 'そうなる時',               kind: 'world-recall-when2' },
  { surface: 'そうなったら',             kind: 'world-recall-cond' },
  { surface: 'そうなれば',               kind: 'world-recall-cond2' },
  { surface: 'そういう時',               kind: 'world-recall-case' },
  { surface: 'そうした時',               kind: 'world-recall-case2' },
  { surface: 'そうした',                 kind: 'anaphoric-perfective' },
  { surface: 'そうやって',               kind: 'anaphoric-manner' },

  // ===== deontic / volitive =====
  { surface: 'なければなりません',       kind: 'deontic-must-pol' },
  { surface: 'なければならない',         kind: 'deontic-must' },
  { surface: 'なければいけません',       kind: 'deontic-must-pol2' },
  { surface: 'なければいけない',         kind: 'deontic-must2' },
  { surface: 'なきゃいけない',           kind: 'deontic-must-c' },
  { surface: 'なきゃならない',           kind: 'deontic-must-c2' },
  { surface: 'なくてはいけない',         kind: 'deontic-must3' },
  { surface: 'なくてはならない',         kind: 'deontic-must4' },
  { surface: 'べきです',                 kind: 'normative-pol' },
  { surface: 'べきだ',                   kind: 'normative' },
  { surface: 'べきではない',             kind: 'normative-neg' },
  { surface: 'べき',                     kind: 'normative-n' },
  { surface: 'たほうがいい',             kind: 'advice-better' },
  { surface: 'たほうがよい',             kind: 'advice-better-formal' },
  { surface: 'たいです',                 kind: 'volitive-pol' },
  { surface: 'たいな',                   kind: 'volitive-soft' },

  // ===== aspectual / benefactive (often pre-final) =====
  { surface: 'てしまいました',           kind: 'aspect-completive-past-pol' },
  { surface: 'てしまった',               kind: 'aspect-completive-past' },
  { surface: 'てしまう',                 kind: 'aspect-completive' },
  { surface: 'ちゃった',                 kind: 'aspect-completive-c' },
  { surface: 'ちゃう',                   kind: 'aspect-completive-c2' },
  { surface: 'てある',                   kind: 'aspect-resultant' },
  { surface: 'ておく',                   kind: 'aspect-anticipatory' },
  { surface: 'とく',                     kind: 'aspect-anticipatory-c' },
  { surface: 'てくる',                   kind: 'aspect-deictic-come' },
  { surface: 'ていく',                   kind: 'aspect-deictic-go' },
  { surface: 'てみる',                   kind: 'aspect-attemptive' },
  { surface: 'てごらん',                 kind: 'aspect-try-cmd' },
  { surface: 'てあげる',                 kind: 'benefactive-down' },
  { surface: 'てくれる',                 kind: 'benefactive-in' },
  { surface: 'てもらう',                 kind: 'benefactive-receive' },
  { surface: 'ていただく',               kind: 'benefactive-receive-pol' },

  // ===== topic / focus particles (multi-char only — single-char は・も handled elsewhere) =====
  { surface: 'については',               kind: 'topic-regarding' },
  { surface: 'に関しては',               kind: 'topic-regarding-formal' },
  { surface: 'に関して',                 kind: 'regarding' },
  { surface: 'にとっては',               kind: 'topic-from-perspective' },
  { surface: 'にとって',                 kind: 'from-perspective' },
  { surface: 'において',                 kind: 'locus-formal' },
  { surface: 'における',                 kind: 'locus-attr' },

  // ===== DECISION / INCEPTIVE / VOLITIONAL =====
  { surface: 'ことにします',             kind: 'decision-nominalize-pol' },
  { surface: 'ことにする',               kind: 'decision-nominalize' },
  { surface: 'ことにした',               kind: 'decision-nominalize-past' },
  { surface: 'ことにしました',           kind: 'decision-nominalize-past-pol' },
  { surface: 'ことになります',           kind: 'inceptive-nominalize-pol' },
  { surface: 'ことになる',               kind: 'inceptive-nominalize' },
  { surface: 'ことになった',             kind: 'inceptive-nominalize-past' },
  { surface: 'ことになりました',         kind: 'inceptive-nominalize-past-pol' },
  { surface: 'ようにします',             kind: 'volitional-aim-pol' },
  { surface: 'ようにする',               kind: 'volitional-aim' },
  { surface: 'ようになります',           kind: 'inceptive-state-pol' },
  { surface: 'ようになる',               kind: 'inceptive-state' },
  { surface: 'ようになった',             kind: 'inceptive-state-past' },
  { surface: 'ようになっている',         kind: 'inceptive-state-progressive' },

  // ===== HORTATIVE / PROPOSAL =====
  { surface: 'ていきましょう',           kind: 'hortative-go-pol' },
  { surface: 'ていこうと思います',       kind: 'hortative-think-pol' },
  { surface: 'ていこうと思う',           kind: 'hortative-think' },
  { surface: 'ていこう',                 kind: 'hortative-go' },
  { surface: 'ていきます',               kind: 'aspect-deictic-go-pol' },
  { surface: 'ていきたい',               kind: 'volitive-go' },
  { surface: 'ていきたいと思います',     kind: 'volitive-go-think' },
  { surface: 'ましょう',                 kind: 'hortative-pol' },
  { surface: 'ようと思います',           kind: 'volitive-think-pol' },
  { surface: 'ようと思う',               kind: 'volitive-think' },
  { surface: 'ようかな',                 kind: 'volitive-self' },

  // ===== EXPERIENTIAL =====
  { surface: 'たことがあります',         kind: 'experiential-past-pol' },
  { surface: 'たことがある',             kind: 'experiential-past' },
  { surface: 'たことある',               kind: 'experiential-past-c' },
  { surface: 'たことありますか',         kind: 'experiential-q-pol' },
  { surface: 'たことある?',              kind: 'experiential-q-c' },
  { surface: 'たことある？',             kind: 'experiential-q-c2' },
  { surface: 'たことありません',         kind: 'experiential-neg-pol' },
  { surface: 'たことがない',             kind: 'experiential-neg' },
  { surface: 'たことない',               kind: 'experiential-neg-c' },
  { surface: 'たことなくて',             kind: 'experiential-neg-gerund' },

  // ===== PASSIVE / HEARSAY-PASSIVE =====
  { surface: 'と言われています',         kind: 'passive-hearsay-prog-pol' },
  { surface: 'と言われている',           kind: 'passive-hearsay-prog' },
  { surface: 'と言われていた',           kind: 'passive-hearsay-prog-past' },
  { surface: 'と言われました',           kind: 'passive-hearsay-pol' },
  { surface: 'と言われた',               kind: 'passive-hearsay-past' },
  { surface: 'と言われ',                 kind: 'passive-hearsay-stem' },
  { surface: 'って言われています',       kind: 'passive-hearsay-prog-pol-c' },
  { surface: 'って言われている',         kind: 'passive-hearsay-prog-c' },
  { surface: 'って言われていた',         kind: 'passive-hearsay-prog-past-c' },
  { surface: 'って言われた',             kind: 'passive-hearsay-past-c' },
  { surface: 'って言われ',               kind: 'passive-hearsay-stem-c' },
  { surface: 'と言われてしまった',       kind: 'regretful-passive' },
  { surface: 'と言われてしまいました',   kind: 'regretful-passive-pol' },
  { surface: 'って言われてしまった',     kind: 'regretful-passive-c' },
  { surface: 'と呼ばれている',           kind: 'passive-call-prog' },
  { surface: 'と呼ばれていた',           kind: 'passive-call-prog-past' },
  { surface: 'と呼ばれる',               kind: 'passive-call' },
  { surface: 'と呼ばれた',               kind: 'passive-call-past' },
  { surface: 'と思われる',               kind: 'passive-think' },
  { surface: 'と思われます',             kind: 'passive-think-pol' },
  { surface: 'と思われている',           kind: 'passive-think-prog' },
  { surface: 'と称される',               kind: 'passive-titled' },
  { surface: 'と称された',               kind: 'passive-titled-past' },

  // ===== UNIVERSAL / EXEMPLIFICATION =====
  { surface: 'を問わない',               kind: 'universal-no-distinction' },
  { surface: 'を問わず',                 kind: 'universal-no-distinction2' },
  { surface: 'にかかわらず',             kind: 'universal-regardless' },
  { surface: 'に関わらず',               kind: 'universal-regardless2' },
  { surface: 'たりする',                 kind: 'non-exhaustive-exemplify' },
  { surface: 'たりします',               kind: 'non-exhaustive-exemplify-pol' },
  { surface: 'たりした',                 kind: 'non-exhaustive-exemplify-past' },
  { surface: 'たりしました',             kind: 'non-exhaustive-exemplify-past-pol' },
  { surface: 'たりして',                 kind: 'non-exhaustive-exemplify-gerund' },
  { surface: 'などといった',             kind: 'exemplify-cite' },
  { surface: 'などの',                   kind: 'exemplify-of' },

  // ===== FRAMING / CRITERION =====
  { surface: 'としては',                 kind: 'framing-as-topic' },
  { surface: 'としても',                 kind: 'framing-as-concede' },
  { surface: 'として',                   kind: 'framing-as' },
  { surface: 'で言えば',                 kind: 'criterion-if-said' },
  { surface: 'で言うと',                 kind: 'criterion-if-said2' },
  { surface: 'で言いますと',             kind: 'criterion-if-said-pol' },
  { surface: 'からすると',               kind: 'criterion-from' },
  { surface: 'からすれば',               kind: 'criterion-from2' },
  { surface: '的に言えば',               kind: 'criterion-categorical' },
  { surface: '的に言うと',               kind: 'criterion-categorical2' },

  // ===== META-SEGUE / REASON-FRAME =====
  { surface: 'というわけで',             kind: 'meta-segue' },
  { surface: 'そんなわけで',             kind: 'meta-segue2' },
  { surface: 'そういうわけで',           kind: 'meta-segue3' },
  { surface: 'ってわけで',               kind: 'meta-segue-c' },
  { surface: 'わけですけれども',         kind: 'reason-concede' },
  { surface: 'わけですけども',           kind: 'reason-concede' },
  { surface: 'わけですけど',             kind: 'reason-concede' },
  { surface: 'わけだけど',               kind: 'reason-concede' },
  { surface: 'わけですから',             kind: 'reason-cause' },
  { surface: 'わけだから',               kind: 'reason-cause' },
  { surface: 'わけでして',               kind: 'reason-ground' },
  { surface: 'わけですよね',             kind: 'reason-align' },
  { surface: 'わけですよ',               kind: 'reason-reveal' },
  { surface: 'わけだよ',                 kind: 'reason-reveal' },
  { surface: 'わけですね',               kind: 'reason-align' },
  { surface: 'わけだね',                 kind: 'reason-align' },
  { surface: 'わけです',                 kind: 'reason-state' },
  { surface: 'わけで',                   kind: 'reason-ground' },
  { surface: 'わけだ',                   kind: 'reason-state' },

  // ===== META-DISCOURSE-REF =====
  { surface: 'という話',                 kind: 'meta-discourse-noun' },
  { surface: 'って話',                   kind: 'meta-discourse-noun-c' },
  { surface: 'というのが',               kind: 'meta-discourse-subj' },
  { surface: 'っていうのが',             kind: 'meta-discourse-subj-c' },
  { surface: 'みたいな話',               kind: 'hypothetical-world-label' },
  { surface: 'みたいなこと',             kind: 'hypothetical-world-label2' },
  { surface: 'みたいな設計',             kind: 'design-ascription' },
  { surface: 'みたいな感じ',             kind: 'approximative-feeling' },

  // ===== POSSESSIVE-MOTIVE =====
  { surface: 'の願い',                   kind: 'possessive-motive-wish' },
  { surface: 'の意志',                   kind: 'possessive-motive-will' },
  { surface: 'のつもり',                 kind: 'possessive-motive-intent' },
  { surface: 'の気持ち',                 kind: 'possessive-motive-feeling' },
  { surface: 'の思い',                   kind: 'possessive-motive-thought' },
  { surface: 'の意図',                   kind: 'possessive-motive-intention' },

  // ===== ADDITIVE / SCOPE-EXTEND =====
  { surface: 'というのも',               kind: 'additive-meta' },
  { surface: 'っていうのも',             kind: 'additive-meta-c' },
  { surface: 'でもね',                   kind: 'particle-even-soft' },
  { surface: 'でさえ',                   kind: 'scalar-even' },
  { surface: 'すら',                     kind: 'scalar-even-stronger' },

  // ===== EXCLAMATIVES / DISCOVERY =====
  { surface: 'あら、',                   kind: 'exclamative-mild' },
  { surface: 'あれ、',                   kind: 'exclamative-confusion' },
  { surface: 'おお、',                   kind: 'exclamative-impressed' },
  { surface: 'お、',                     kind: 'exclamative-discovery' },
  { surface: 'え、',                     kind: 'exclamative-surprise' },
  { surface: 'えっ、',                   kind: 'exclamative-surprise2' },
  { surface: 'へえ、',                   kind: 'exclamative-realization' },
  { surface: 'へー、',                   kind: 'exclamative-realization2' },
  { surface: 'ほー、',                   kind: 'exclamative-impressed2' },
  { surface: 'おっと、',                 kind: 'exclamative-caught' },

  // ===== EXPLANATORY-Q / EXPERIENTIAL-Q markers =====
  { surface: 'のですか',                 kind: 'explanatory-q-pol' },
  { surface: 'んですか',                 kind: 'explanatory-q' },
  { surface: 'んですか?',                kind: 'explanatory-q-mark' },
  { surface: 'んですか？',               kind: 'explanatory-q-mark2' },
  { surface: 'のか',                     kind: 'explanatory-q-c' },
  { surface: 'のかな',                   kind: 'explanatory-q-soft' },
  { surface: 'の?',                      kind: 'explanatory-q-min' },
  { surface: 'の？',                     kind: 'explanatory-q-min2' },

  // ===== META-CONFIRM =====
  { surface: 'そうなんだけど',           kind: 'meta-confirm-concede' },
  { surface: 'そうなんですけど',         kind: 'meta-confirm-concede-pol' },
  { surface: 'そうなんですけれども',     kind: 'meta-confirm-concede-pol2' },
  { surface: 'そうなんだよね',           kind: 'meta-confirm-shared' },
  { surface: 'そうなんですよね',         kind: 'meta-confirm-shared-pol' },
  { surface: 'そうなんだよ',             kind: 'meta-confirm-assert' },
  { surface: 'そうなんですよ',           kind: 'meta-confirm-assert-pol' },
  { surface: 'そうなんです',             kind: 'meta-confirm-pol' },
  { surface: 'そうなんだ',               kind: 'meta-confirm' },

  // ===== TOPIC-INTRODUCE-INTIMATE =====
  { surface: 'これね、',                 kind: 'topic-intro-this' },
  { surface: 'それね、',                 kind: 'topic-intro-it' },
  { surface: 'あれね、',                 kind: 'topic-intro-that' },
  { surface: 'これがね、',               kind: 'topic-intro-this-subj' },
  { surface: 'それがね、',               kind: 'topic-intro-it-subj' },

  // ===== CHARACTER ASCRIPTION =====
  { surface: 'であり',                   kind: 'copula-coord' },
  { surface: 'であって',                 kind: 'copula-coord2' },
  { surface: 'でありながら',             kind: 'copula-concede' },
];

// Sort by surface length DESC so longest-match-first tokenization is correct.
export const COMPOUNDS = [...RAW_COMPOUNDS].sort((a, b) => b.surface.length - a.surface.length);

/** Index by first char for fast lookup during scanning. */
export const COMPOUND_INDEX = (() => {
  const m = new Map();
  for (const c of COMPOUNDS) {
    const k = c.surface[0];
    if (!m.has(k)) m.set(k, []);
    m.get(k).push(c);
  }
  return m;
})();

/** Quick lookup table from surface → kind. */
export const COMPOUND_BY_SURFACE = new Map(COMPOUNDS.map(c => [c.surface, c]));
