/**
 * catalog-mirror.ts — the vault-native mirror of the pattern catalog + gold
 * store (AUDIT §1.3.3, punch list #6).
 *
 * The attestation corpus is the plugin's actual product, and until now it
 * lived ONLY inside the plugin-data blob. The mirror writes it into the vault
 * as plain files after every change:
 *
 *   <folder>/catalog.jsonl        — one PatternEntry per line, sorted by id
 *                                    (stable diffs); the RESTORE source.
 *   <folder>/catalog.md           — human-readable index by class.
 *   <folder>/discourse-gold.jsonl — the 🔴 gold examples (append-shaped:
 *                                    regenerated whole, but line-per-example).
 *
 * Files-over-app: the corpus survives the plugin dying, diffs in git, syncs
 * as text, and stays greppable. The blob remains the runtime truth; the
 * mirror is the durable copy — `restore-catalog-from-mirror` reads it back.
 *
 * PURE renderers/parser — no Obsidian imports — golden-tested in
 * golden/mirror.mjs. The debounced writer lives in main.ts.
 */

import type { PatternEntry } from './pattern-store.ts';
import { NOTE_TYPES, NOTE_CLASSES, type NoteClass } from './note-types.ts';

/** Stable, diff-friendly: sorted by id, one JSON object per line. */
export function renderCatalogJsonl(entries: PatternEntry[]): string {
  return [...entries]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((e) => JSON.stringify(e))
    .join('\n') + (entries.length ? '\n' : '');
}

/** Parse the mirror back. Skips malformed lines; validates the minimal shape. */
export function parseCatalogJsonl(text: string): PatternEntry[] {
  const out: PatternEntry[] = [];
  for (const line of text.split('\n')) {
    const t = line.trim();
    if (!t) continue;
    try {
      const e = JSON.parse(t) as PatternEntry;
      if (e && typeof e.id === 'string' && typeof e.key === 'string' && typeof e.class === 'string') {
        out.push(e);
      }
    } catch { /* malformed line — skip, keep restoring the rest */ }
  }
  return out;
}

/** Human-readable index: grouped by class, confirmed/suggested counts.
 *  Deliberately timestamp-free: identical catalog → identical file, so the
 *  idempotent writer can skip unchanged writes (no sync churn). */
export function renderCatalogMd(entries: PatternEntry[]): string {
  const byClass = new Map<NoteClass, PatternEntry[]>();
  for (const e of entries) {
    const list = byClass.get(e.class) ?? [];
    list.push(e);
    byClass.set(e.class, list);
  }
  const lines: string[] = [
    '# パターン台帳（自動ミラー）',
    '',
    `> ${entries.length} patterns — regenerated by jp-collocations on every change.`,
    `> Machine copy: \`catalog.jsonl\` (restore via the`,
    `> "台帳: Restore Catalog from Vault Mirror" command).`,
    '',
  ];
  for (const cls of NOTE_CLASSES) {
    const list = byClass.get(cls);
    if (!list?.length) continue;
    const def = NOTE_TYPES[cls];
    lines.push(`## ${def.emoji} ${def.label} (${list.length})`, '');
    for (const e of [...list].sort((a, b) => b.updatedAt - a.updatedAt)) {
      const confirmed = e.attestations.filter((a) => !a.status).length;
      const suggested = e.attestations.length - confirmed;
      const gloss = e.payload.gloss ? ` — ${e.payload.gloss}` : '';
      const att = confirmed || suggested
        ? ` 〔${confirmed}件${suggested ? ` +候補${suggested}` : ''}〕`
        : '';
      lines.push(`- **${e.key}**${gloss}${att}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
